accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:movie_pk>/edit/<int:score_pk>/', views.edit_score, name="edit_score"),
    path('<int:user_pk>/',views.profile,name="profile"),
    path('<int:user_pk>/follow/',views.follow,name="follow"),
    path('<int:user_pk>/create_profile/', views.create_profile, name="create_profile"),

    # 관리자 모드 -----------------------------------
    path('test/algorithm_clear/',views.algorithm_clear, name="test_algorithm_clear"),
    path('test/make_bot/',views.make_bot, name="test_make_bot"),
    path('test/make_bot_score/',views.make_bot_score, name="make_bot_score"),
    path('test/search_sns/<int:num>/',views.search_sns, name="search_sns"),
]

actors/urls.py
from django.urls import path
from . import views

app_name = 'actors'

urlpatterns = [
    path('', views.actors_list, name='actors_list'), 
    path('<int:actor_pk>/', views.actor_detail, name='actor_detail'), 
]

movie_recommend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('actors/', include('actors.urls')),
    
    # OAuth 적용 위함
    path('accounts/', include('allauth.urls')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('', views.index, name="movie_index"), 
    path('movielist/', views.movie_lists, name='movie_list'), ##
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'), 
    path('genre/', views.genre_list, name='genre_list'), 
    path('genre/<int:genre_id>/', views.genre_movies, name='genre_movies'), 
    path('director/<int:director_id>/', views.director, name='director'),
    
    # score 를 삭제하는 url입니다. score 생성은 movie_detail에서 다루고 있습니다.
    path('<int:movie_id>/delete_score/<int:score_id>/', views.delete_score, name="delete_score"), 
    
    # 추천하는 영화를 출력하는 url
    path('out_movie/', views.out_movie, name="out_movie"),
    
    # 첫 화면에서 review it 하면 전체 영화 리스트를 보여주고, 해당 영화의 이미지를 누르면 detail로 이동하게 됩니다.
    path('evaluate/', views.movie_evaluate, name="movie_evaluate"),
    
    # movie_list.html 에서 영화를 검색하면 해당 영화이름을 가지고 있는 영화들을 보여줍니다.
    path('search_movie/<str:movie_title>/', views.search_movie, name="search_movie"),
    
    #
    path('view_movies/<str:movie_title>', views.view_movies, name="view_movies"),
]

movies/models.py
from django.db import models
# Create your models here.

# genre.json import 방법:
# $ python manage.py loaddata genre.json
class Genre(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

class Director(models.Model):
    name = models.CharField(max_length=100)
    imageurl = models.CharField(max_length=100)
    birthday = models.CharField(max_length=40, blank=True)
    def __str__(self):
        return self.name
    
class Movie(models.Model):
    
    title = models.CharField(max_length=100)
    imageurl = models.CharField(max_length=100)
    director = models.ForeignKey(Director, blank=True, on_delete=models.CASCADE)
    release_date = models.CharField(max_length=20)
    overview = models.CharField(max_length=1000, default='')
    
    genres = models.ManyToManyField(Genre, related_name = 'genre_movies', blank=True)
    
    def __str__(self):
        return self.title
        
        
#-----------------------------------------------------------

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from django.db.models import Avg
from .models import Movie, Genre, Director
from actors.models import Actor
from accounts.models import *
from accounts.forms import ScoreForm

from django.http import JsonResponse

# Create your views here.
# genre.json import 방법:
# $ python manage.py loaddata genre.json

def show_movies(me):
    out_len = 10
    out = []

    for movie in Movie.objects.all():
        if movie in me.score_set.all():
            continue
        
        man_score = 0.0
        cnt = 0
        for score in movie.movie_scores.all():
            temp = 0
            if Me_you_similar.objects.filter(me = me , you = score.user):
                temp = Me_you_similar.objects.filter(me = me , you = score.user)[0].out()
            elif Me_you_similar.objects.filter(me = score.user , you = me):
                temp = Me_you_similar.objects.filter(me = score.user , you = me)[0].out()
            temp *= score.score
            man_score += temp
            cnt += 1
                
        if cnt==0 or man_score < 0: continue
        man_score /= cnt
        if len(out)<out_len: out.append([movie,man_score])
        elif out[out_len-1][1] < man_score: out[out_len-1] = [movie,man_score]

        for i in range(len(out)-1,0,-1):
            if out[i][1] > out[i-1][1]: out[i] , out[i-1] = out[i-1] , out[i]
            else: break
    return out #[movie[0] for movie in out]
    
def show_genre():
    out_len = 10
    out = []
    for genre in Genre.objects.all():
        sums = 0
        cnt = 0
        for movie in Movie.objects.filter(genres__in=[genre]):
            for score in Score.objects.filter(movie = movie):
                sums += score.score
                cnt += 1
        if cnt==0: continue
        elif len(out)<out_len: out.append([genre,sums/cnt])
        elif out[out_len-1][1] < sums/cnt: out[out_len-1] = [genre,sums/cnt]
        
        for i in range(len(out)-1,0,-1):
            if out[i][1] > out[i-1][1]: out[i] , out[i-1] = out[i-1] , out[i]
            else: break

    output = []
    for genre in out:
        for movie in Movie.objects.filter(genres__in=[genre[0]]):
            sum_score , score_cnt = 0 , 0
            for score in movie.movie_scores.all():
                sum_score += score.score
                score_cnt+=1
            out_avg = sum_score/score_cnt if score_cnt else 0
            output.append([movie,out_avg])
            if len(output)>=out_len: break
        if len(output)>=out_len: break
    
    return output
        
def show_bestmovies():

    movies_out = {}
    scores = Score.objects.all()
    
    for score in scores:
        movie = score.movie
        score_num = score.score
    
        if movie not in movies_out:
            movies_out.update({f'{movie}':[score_num, 1, score_num]})
        else:
            movies_out[f'{movie}'][0] += score_num
            movies_out[f'{movie}'][1] += 1

    for i in movies_out:
        movies_out[i][2] = movies_out[i][0] / movies_out[i][1]
    
    sorted_movies_out = sorted(movies_out.items(), key=lambda item:item[1][2], reverse=True)
    movies_output = []
    
    for sorted_movie in sorted_movies_out:
        movie = Movie.objects.filter(title=sorted_movie[0]).first()
        movies_output.append([movie, sorted_movie[1][2]])
    
    return movies_output

#-----------------------------------------------------------

def index(request):
    return render(request, 'movies/index.html')

def movie_lists(request):
    
    if not request.user.is_authenticated:
        return redirect("accounts:login")
        
    scores = len(Score.objects.filter(user=request.user).all()) # 회원이 score를 남기지 않은 경우에는 그 사람이 좋아하는 장르를 우선적으로 노출시키겠습니다.

    movies = show_movies(request.user)
    best_genre = show_genre() # 신욱형이 만든 장르별 영화추천
    best_movies = show_bestmovies() # 김슬기가 만든 영화추천
    
    movies = movies[2:] + movies[0:2]
    best_genre = best_genre[2:] + best_genre[0:2]
    best_movies = best_movies[2:] + best_movies[0:2]

    context = {'movies':movies,'best_genre':best_genre, 'best_movies':best_movies, 'scores':scores}
    
    return render(request, 'movies/movies_list.html', context)
    
def movie_detail(request, movie_id):
    
    movie = get_object_or_404(Movie, pk=movie_id)
    
    if request.method=='POST':
        score_form = ScoreForm(request.POST)
        if score_form.is_valid() and request.POST.get('score') and not(movie.movie_scores.filter(user=request.user)):
            score = score_form.save(commit=False)
            # 넘어 온 것 중 그것
            score.score = request.POST.get('score')
            score.movie = movie
            score.user = request.user
            score.save()
            for silmilar in request.user.me_similar.all():
                silmilar.add_movie(movie)
                silmilar.save()
            for silmilar in request.user.you_similar.all():
                silmilar.add_movie(movie)
                silmilar.save()
            
        return redirect('movies:movie_detail', movie_id)
                
    else:
        score_form = ScoreForm()

    context = {'movie':movie, 'score_form':score_form}
    return render(request, 'movies/movie_detail.html', context)
    
def genre_list(request):
    genres = Genre.objects.all()
    context = {'genres':genres}
    return render(request, 'movies/genres_list.html',context)
    
def genre_movies(request, genre_id):
    genre = get_object_or_404(Genre, pk=genre_id)
    context = {'genre':genre}
    return render(request, 'movies/genre_movies.html', context)
    
def director(request, director_id):
    director = get_object_or_404(Director, pk=director_id)
    context = {'director':director}
    return render(request, 'movies/director.html',context)

@login_required       
def movie_evaluate(request):
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    context = {'movies':movies, 'genres':genres}
    return render(request, 'movies/movie_evaluate.html', context)
  
@login_required
@require_POST
def delete_score(request, movie_id, score_id):
    score = get_object_or_404(Score, pk=score_id)
    movie = get_object_or_404(Movie, pk=movie_id)
    
    if request.user == score.user:
        for silmilar in request.user.me_similar.all():
            silmilar.remove_movie(movie)
            silmilar.save()
        for silmilar in request.user.you_similar.all():
            silmilar.remove_movie(movie)
            silmilar.save()
        score.delete()
    return redirect('movies:movie_detail', movie_id)


# movies/movielist 에서 영화검색! 쪽에 이름을 올리면 비동기적으로 이름을 포함하고 있는 영화들을 반환합니다.
def search_movie(request, movie_title):
    movies = Movie.objects.filter(title__contains=movie_title)
    print(movies)
    result = list(movies.values())
    return JsonResponse(result, safe=False)
    
# movies/movielist 의 영화검색에서 엔터를 치면 해당 이름을 가지는 영화들을 보여주는 페이지로 이동하기 위해 만든 view-html 함수입니다.
def view_movies(request, movie_title):
    movies = Movie.objects.filter(title__contains=movie_title)
    context = {'movies': movies}
    return render(request, 'movies/view_movies.html', context)


#------------------------------------------------



def out_movie(request):
    context={'out':show_movies()}
    return render(request, 'movies/out_movie.html', context)
    

    

movies/templates/movies/actor_movies.html
{% for movie in actor.movies.all %}
<span>{{movie}}</span><br><br>
{% endfor %}
<br><br><br><br>
{{actor.name}}<br>
{{actor.birthday}}<br>

movies/templates/movies/director.html
{% for movie in director.movie_set.all %}
{{movie}}<br>
{% endfor %}

movies/templates/movies/genre_list.html
{% for genre in genres %}
<span><a href="{% url 'movies:genre_movies' genre.id %}">{{genre}}</a>:</span>
    {% for movie in genre.genre_movies.all %}
        <span>{{movie}},</span>
    {% endfor %}
    
    <br><br><br>
{% endfor %}

movies/templates/movies/genre_movies.html
{% for movie in genre.genre_movies.all %}
<a href="{% url 'movies:movie_detail' movie.id %}">{{movie}}</a><br>
{% endfor %}

movies/templates/movies/genres_list.html
<ul>
{% for genre in genres %}
    <li>
        <span><a href="{% url 'movies:genre_movies' genre.id %}">{{genre}}</a>:</span>
            {% for movie in genre.genre_movies.all %}
                <p>{{movie}}</p>
            {% endfor %}
            
            <br><br><br>  
    </li>

{% endfor %}
</ul>

movies/templates/movies/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<link rel="stylesheet" href="/ovie_recommend/assets/movies/index.css">-->
    <link rel="stylesheet" href="{% static 'movies/index.css' %}">
    <link rel="stylesheet" media="(max-width:600px)" href="{% static 'movies/index-2-small.css' %}">
    <!-- <link rel="stylesheet" media="(min-width:601px)" href="index-2-large.css"> -->
    <link rel="stylesheet" href="{% static 'movies/hamburger.css' %}">
    <link rel="icon" href="{% static 'favicon.png' %}" sizes="16x16" type="image/png">
    
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR|Teko" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
        integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'movies/evaluate.css' %}">
    <title>Blockbuster</title>

    <script src="https://unpkg.com/scrollreveal"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>

<body>

    <section id="main-app">
        
        <div id="preloader">
            <div id="loader"></div>
            <p id="loader-text" style="
                                font-family: 'Noto Sans KR', 'Teko', sans-serif;
                                color: white !important;
                                font-size: 3rem;
                                display: inline-block;
                                width: 100%;
                                text-align: center !important;
                                z-index: 10000000000000;
                                margin-top: 8%;
                                font-weight: bold;
            
            ">하늘도 예쁘고 달도 예쁜날에 너는 오죽할까</p>
        </div>
        
        <div id="index-background">
            <!-- navigation bar -->
            <nav>
                <div id="nav-logo">
                    <a href="{% url 'movies:movie_index' %}"><img src="{% static 'logo.png' %}" alt=""></a>
                </div>
                <div id="nav-auth">
                    <!-- <button class="openbtn" onclick="openNav()">&#9776;</button>. -->
                    <button id="hamburgerBtn" class="openbtn closebtn hamburger hamburger--collapse "
                        onclick="hamburger()" type="button">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
                <div id="nav-collapsed-side-bar">
                    <a href="{% url 'movies:movie_list' %}">For you</a>
                    <a href="{% url 'movies:movie_evaluate' %}">Select Genre</a>
                    {% if user_is.authenticated == False %}
                    <a href="{% url 'accounts:signup' %}">Sign Up</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}">Logout</a>
                    {% endif %}
                    <hr id="nav-collapsed-side-bar-hr">
                    <div id="nav-collapsed-side-bar-quote">
                        <p>Remember Red, hope is a good thing. maybe the best of things,
                            and no good thing ever dies.
                            <br><br> - Shawshank Redemption
                        </p>
                    </div>
                </div>
            </nav>
            <!-- main contents -->
            <div id="index-background-content">
                <div id="index-background-content-left">
                    <h1>영화 <span id="index-background-content-left-inner">보기 <br>참 좋은 날</span></h1>
                    <hr id="index-background-content-left-bar">
                    <p style="text-align:left !important;">그대를 위한 영화를 추천해드려요.</p>
                    <div id="index-background-content-left-signup-box">
                        {% if user.is_authenticated %}
                            <a id="index-background-content-left-signup" class="loginBtn" href="{% url 'movies:movie_list' %}" style="
                            display: inline-block; width: 40%" @click="goToForYou()">추천영화보기</a>
                        {% else %}
                            <a id="index-background-content-left-signup" class="loginBtn" href="{% url 'accounts:login' %}">Login</a>
                        {% endif %}
                    </div>
                </div>
                <div id="index-background-content-right">

                </div>
            </div>
        </div>
        <div id="small-index-background-2">
            <p>Life moves pretty fast, if you don't stop<br> and look around once in a while,<br>
                you could miss it. 
                <br> - Ferris Bueller's Day Off
            </p>
        </div>
    </section>

    <footer>
        <p>© 2019 Blockbuster, Inc. Designed by Bbangul.</p>
    </footer>
    <script>

        
        // nav side bar function    
        let sideBarStatus = false
        function openNav() {
            document.getElementById("nav-collapsed-side-bar").style.width = "400px";
            document.getElementById("nav-auth").style.marginLeft = "250px";
        }

        /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
        function closeNav() {
            document.getElementById("nav-collapsed-side-bar").style.width = "0";
            document.getElementById("nav-auth").style.marginLeft = "0";
        }
            
        // hamburger trigger
        function hamburger() {
            const hamburgerClassList = document.querySelector("#hamburgerBtn")
            const navSideBar = document.querySelector('#nav-collapsed-side-bar')
            if (hamburgerClassList.classList.contains("is-active")) {
                hamburgerClassList.classList.remove("is-active")
                document.getElementById("nav-collapsed-side-bar").style.width = "0";
                document.getElementById("nav-auth").style.marginLeft = "0";
                document.getElementById("nav-auth").style.zIndex = '100';
                navSideBar.style.zIndex = '1';
            } else {
                hamburgerClassList.classList.add("is-active")
                document.getElementById("nav-collapsed-side-bar").style.width = "400px";
                document.getElementById("nav-auth").style.marginLeft = "250px";
                document.getElementById("nav-auth").style.zIndex = '100';
                navSideBar.style.zIndex = '1';
            }
        }
    </script>
    
    <!--vue-->
    <script>
        const mainApp = new Vue({
            el: '#main-app',
            data: '',
            methods: {
                goToForYou : function() {
                    const preLoader = document.querySelector('#preloader')
                    axios.interceptors.request.use(function (config) {
                            // Do something before request is sent
                            preLoader.style.display = "block"
                            return config
                          }, function (error) {
                            // Do something with request error
                            console.log("egg");
                          });
                    axios.get(`/movies/movielist/`)
                        .then(response => 
                        
                        window.location.replace("/movies/movielist/")
                        
                        )
                    
                },
            },
        })
        
    </script>
</body>

</html>

movies/templates/movies/out_movie.html
{{out}}

movies/templates/movies/view_movies.html
<h1>검색 결과에 따른 영화목록</h1>
{% for movie in movies %}
<a href="{% url 'movies:movie_detail' movie.id %}">{{movie}}</a>
<br>
{% endfor %}