accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:movie_pk>/edit/<int:score_pk>/', views.edit_score, name="edit_score"),
    path('<int:user_pk>/',views.profile,name="profile"),
    path('<int:user_pk>/follow/',views.follow,name="follow"),
    path('<int:user_pk>/create_profile/', views.create_profile, name="create_profile"),

    # 관리자 모드 -----------------------------------
    path('test/algorithm_clear/',views.algorithm_clear, name="test_algorithm_clear"),
    path('test/make_bot/',views.make_bot, name="test_make_bot"),
    path('test/make_bot_score/',views.make_bot_score, name="make_bot_score"),
    path('test/search_sns/<int:num>/',views.search_sns, name="search_sns"),
]

actors/urls.py
from django.urls import path
from . import views

app_name = 'actors'

urlpatterns = [
    path('', views.actors_list, name='actors_list'), 
    path('<int:actor_pk>/', views.actor_detail, name='actor_detail'), 
]

movie_recommend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('actors/', include('actors.urls')),
    
    # OAuth 적용 위함
    path('accounts/', include('allauth.urls')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('', views.index, name="movie_index"), 
    path('movielist/', views.movie_lists, name='movie_list'), ##
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'), 
    path('genre/', views.genre_list, name='genre_list'), 
    path('genre/<int:genre_id>/', views.genre_movies, name='genre_movies'), 
    path('director/<int:director_id>/', views.director, name='director'),
    
    # score 를 삭제하는 url입니다. score 생성은 movie_detail에서 다루고 있습니다.
    path('<int:movie_id>/delete_score/<int:score_id>/', views.delete_score, name="delete_score"), 
    
    # 추천하는 영화를 출력하는 url
    path('out_movie/', views.out_movie, name="out_movie"),
    
    # 첫 화면에서 review it 하면 전체 영화 리스트를 보여주고, 해당 영화의 이미지를 누르면 detail로 이동하게 됩니다.
    path('evaluate/', views.movie_evaluate, name="movie_evaluate"),
    
    # movie_list.html 에서 영화를 검색하면 해당 영화이름을 가지고 있는 영화들을 보여줍니다.
    path('search_movie/<str:movie_title>/', views.search_movie, name="search_movie"),
    
    #
    path('view_movies/<str:movie_title>', views.view_movies, name="view_movies"),
]

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm

from .models import Score


class UserCustomAuthenticationForm(AuthenticationForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')
        
    def __init__(self, *args, **kwargs):
        super(UserCustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            # 'id': 'user',
            'class': 'input',})
        self.fields['password'].widget = forms.TextInput(attrs={
            # 'id': 'pass',
            'class': 'input',
            'type' : "password",
        })

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'email',)
    
    def __init__(self, *args, **kwargs):
        super(UserCustomCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'id': 'user',
            'class': 'input',})
        self.fields['password1'].widget = forms.PasswordInput(attrs={
            'id': 'pass',
            'class': 'input',
            'type' : "password",
        })
        self.fields['password2'].widget = forms.PasswordInput(attrs={
            'id': 'pass',
            'class': 'input',
            'type' : "password",
        })
        self.fields['email'].widget = forms.TextInput(attrs={
            'id': 'pass',
            'class': 'input',
            # 'type' : "email",
        })
        
    
class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name',)
        

class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields=('content',)
        widgets = {
            'content': forms.Textarea(attrs={'rows':4, 'cols':30}),
        }
        
    def __init__(self, *args, **kwargs):
        super(ScoreForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget = forms.TextInput(attrs={
            'id': 'comment-content',
            'class': 'comment-content-input',})
     

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .forms import UserCustomCreationForm, UserCustomAuthenticationForm

import random

from .models import Me_you_similar,Score,Comment
from accounts.models import Score
from movies.models import Genre, Movie
from actors.models import Actor

# Create your views here.

def index(request):
    return render(request, 'accounts/signin.html')

def signup(request):
    if request.method =='POST':
        print(request.POST)
        user_form = UserCustomCreationForm(request.POST)
        print(user_form)
        if user_form.is_valid():
            print("hello")
            user = user_form.save()
            #-------------------------------
            for you in get_user_model().objects.all():
                if you != user:
                    temp = Me_you_similar(me=user,you=you)
                    temp.update()
                    temp.save()
                
            #-------------------------------
            auth_login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('movies:movie_evaluate')    
    else:
        user_form = UserCustomCreationForm()
        
    context = {'user_form':user_form}
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('accounts:index')
        
    if request.method=='POST':
        login_form = UserCustomAuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:movie_index')
    else:
        login_form = UserCustomAuthenticationForm()
        user_form = UserCustomCreationForm()
        
    context = {'login_form':login_form}
    
    return render(request, 'accounts/signin.html', context)
    
@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:movie_index')
    
def profile(request,user_pk):
    User = get_user_model()
    user = get_object_or_404(User,pk=user_pk)
    me = request.user
    
    if request.method=="POST" and me.is_authenticated and user != me:
        comment = Comment()
        comment.content = request.POST.get('comment_content')
        comment.me = me
        comment.you = user
        comment.save()
    
    context = {'use':user}
    return render(request,'accounts/profile.html',context)

@login_required   
def follow(request,user_pk):
    User = get_user_model()
    user = get_object_or_404(User,pk=user_pk)
    me = request.user
    if user != me:
        if user in me.followers.all():
            me.followers.remove(user)
        else:
            me.followers.add(user)
    return redirect('accounts:profile',user_pk)
    
def create_profile(request, user_pk):
    # 뽑아와서 저장만 한다.
    print(request.POST)
    
    # request.POST = {'genres' : ['드라마', '액션']}
    
    user = get_object_or_404(get_user_model(), pk=user_pk)
    genres = request.POST.get('genres') # dict 형식으로 옵니다.
    
    print(genres) # 판타지,모험    / str 길이는 6
    genres = genres.split(',') # [판타지, 모험]
    
    print(len(genres)) # 2
    print(type(genres)) # list   
    len_profile_genres = len(genres)
    
    if len_profile_genres == 1:
        user.like_genre_1 = Genre.objects.filter(name=genres[0]).first()
    elif len_profile_genres == 2:
        user.like_genre_1 = Genre.objects.filter(name=genres[0]).first()
        user.like_genre_2 = Genre.objects.filter(name=genres[1]).first()
    else:
        user.like_genre_1 = Genre.objects.filter(name=genres[0]).first()
        user.like_genre_2 = Genre.objects.filter(name=genres[1]).first()
        user.like_genre_3= Genre.objects.filter(name=genres[2]).first()
    user.save()
    
    
    return redirect('movies:movie_list')
    
@login_required
@require_POST
def edit_score(request,movie_pk,score_pk):
    score = Score.objects.get(pk = score_pk)
    movie = Movie.objects.get(pk = movie_pk)
    if score.score != request.POST.get('edit_score'):
        for silmilar in request.user.me_similar.all():
            silmilar.remove_movie(movie)
            silmilar.save()
        for silmilar in request.user.you_similar.all():
            silmilar.remove_movie(movie)
            silmilar.save()

        score.score = request.POST.get('edit_score')
        score.content = request.POST.get('edit_score_content')
        score.save()
        
        for silmilar in request.user.me_similar.all():
            silmilar.add_movie(movie)
            silmilar.save()
        for silmilar in request.user.you_similar.all():
            silmilar.add_movie(movie)
            silmilar.save()
    else:
        score.score = request.POST.get('edit_score')
        score.content = request.POST.get('edit_score_content')
        score.save()
            
    
    return redirect('movies:movie_detail',movie_pk)
    

# 관리자 모드 -----------------------------------
@login_required
def algorithm_clear(request):
    for model in Me_you_similar.objects.all():
        model.delete()
        
    users = get_user_model().objects.all()
    for idx in range(len(users)):
        for i in range(idx+1,len(users)):
            model = Me_you_similar(me = users[idx] , you = users[i])
            model.update()
            model.save()
    
    return render(request,'test/test_index.html')
    
@login_required
def make_bot(request):
    cnt = 0
    while cnt < 100:
        User = get_user_model()
        name = '__bot'+str(User.objects.count()+1)
        password = 'admin_bot'
        bot = User(username=name,password=password)
        print('bot :',end='')
        print(bot)
        bot.save()
        
        cnt+=1
    
    return redirect('accounts:test_algorithm_clear')
    
@login_required
def make_bot_score(request):
    idx = 0
    while idx < 100:
        idx+=1
        
        User = get_user_model()
        bots = User.objects.filter(username__startswith = '__bot')
        bot = bots[random.randint(0,len(bots)-1)]
        
        movies = list(Movie.objects.all())
        movie = movies[0]
        i = 0
        while i<len(movies):
            if movies[i].movie_scores.filter(user = bot):
                movies.remove(movies[i])
            else:
                i+=1
        
        if not(len(movies)):
            continue
                
        cut = min(100,len(movies)-1)
        movie = movies[random.randint(0,cut)]
    
        
        score_num = random.randint(1,10)
        content = 'maken by bot'
        
        score = Score(score=score_num , user=bot , movie=movie , content=content)
        score.save()
        
        for silmilar in bot.me_similar.all():
            silmilar.add_movie(movie)
            silmilar.save()
        for silmilar in bot.you_similar.all():
            silmilar.add_movie(movie)
            silmilar.save()

    return render(request,'test/test_index.html')
    
def search_sns(request,num):
    from bs4 import BeautifulSoup
    import requests
    
    actors = Actor.objects.all()#filter(pk=num)
    for actor in actors:
        name = str(actor.name)
        name = name.replace(' ','+')
        url = 'https://search.naver.com/search.naver?query={}'.format(name)
        req = requests.get(url)
        soup = BeautifulSoup(req.text, 'html.parser')
        snss = soup.select('.detail_profile > dd > a')

        # out = ['url : {}'.format(url)]
        for sns in snss:
            text = sns.get('href')
            if 'twitter' in text:
                actor.twitter = text
                # out += ['twitter : {}'.format(actor.twitter)]
            elif 'facebook' in text:
                actor.facebook = text
                # out += ['facebook : {}'.format(actor.facebook)]
            elif 'instagram' in text:
                actor.instagram = text
                # out += ['instagram : {}'.format(actor.instagram)]
        actor.save()
    return render(request,'test/test_index.html')
    

accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>user profile</title>
</head>
<body>
    <h1>{{use.username}}</h1>
    {% if use.image %}
        <img src="{{ use.image.url }}"><br>
    {% endif %}
    
    <p>email - {{use.email}}</p>
    <p>nickname - {{use.nickname}}</p>
    <p>좋아하는 장르</p>
    <ul>
        {% if use.like_genre_1 %}
            <li>{{use.like_genre_1}}</li>
        {% endif %}
        {% if use.like_genre_2 %}
            <li>{{use.like_genre_2}}</li>
        {% endif %}
        {% if use.like_genre_3 %}
            <li>{{use.like_genre_3}}</li>
        {% endif %}
    </ul>
    
    <p>팔로우 받은 숫자 - {{use.followings.all.count}}</p>
    <p>팔로우 한 숫자 - {{use.followers.all.count}}</p>
    {% if user != use %}
        {% if use in user.followers.all %}
            <a href="{% url 'accounts:follow' use.pk %}" data-id="{{this_user.pk}}" id="follow">언팔로우~~</a>
        {% else %}
            <a href="{% url 'accounts:follow' use.pk %}" data-id="{{this_user.pk}}" id="follow">팔로우!</a>
        {% endif %}
    {% endif %}
    
    {% if user != use %}
    <form method="POST">
        <textarea name="comment_content" cols="40" rows="8" ></textarea>
        <input type="submit" value="Submit"/>
    </form>
    {% endif %}
    
    <ul>
    {% for comment use.your_comment.all %}
        <li>
            <a href="{% url 'accounts:profile' comment.me.pk %}">{{comment.me.username}}</a> - {{comment.content}}
        </li>
    {% endfor %}
    </ul>
    
    
</body>
</html>

accounts/templates/accounts/signin.html
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <link rel="stylesheet" href="{% static 'accounts/signin.css' %}">
    <link rel="stylesheet" media="(max-width:600px)" href="{% static 'accounts/signin-2-small.css' %}">
    <link rel="icon" href="{% static 'favicon.png' %}" sizes="16x16" type="image/png">
    <title>Blockbuster - signin</title>
</head>

<body>

    <div id="background"></div>

    <section id="signup">

        <!-- 메인으로 연결 -->
        <div id="signup-logo">
            <a href="{% url 'movies:movie_index' %}"><img src="{% static 'logo.png' %}" alt=""></a>
        </div>

        <!-- 로그인 폼 -->
        <div id="login-box">
            <form action="" method="POST">
                {% csrf_token %}
        
                    <div class="login-html">
                        <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1"
                            class="tab">Sign In</label>
                        <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">
                            <!--SignUp-->
                        </label>
                        {% if user.is_authenticated %}
                            <p> 이미 로그인 되어 있습니다. </p>
                        {% else %}
                        <div class="login-form">
                            <div class="sign-in-htm">
                                <div class="group">
                                    <label for="user" class="label">Username</label>
                                    <!--<input id="user" type="text" class="input">-->
                                    {{login_form.username}}
                                </div>
                                <div class="group">
                                    <label for="pass" class="label">Password</label>
                                    <!--<input id="pass" type="password" class="input" data-type="password">-->
                                    {{login_form.password}}
                                </div>
                                <div class="group">
                                    <input type="submit" class="button" value="Sign In">
                                </div>
                                <div class="hr"></div>
                                <div class="foot-lnk">

                                    <a id="kakao-login" href="{% provider_login_url 'kakao' method='oauth2' %}">카카오톡으로 로그인하기</a><br>
                                    
                                    <a id="github-login" href="{% provider_login_url 'github' method='oauth2' %}">깃허브로 로그인하기</a><br>
                                    
                                    <a id="google-login" href="{% provider_login_url 'google' method='oauth2' %}">구글로 로그인하기</a><br>
                                    <a href="{% url 'accounts:signup' %}">회원가입</a><br><br><br><br>
                                    <a id="forgot-passsword" href="#forgot">비밀번호를 잊으셨나요?</a>
                                </div>
                            </div>
                    {% endif %}
                            <!--<div class="sign-up-htm">-->
                            <!--    <div class="group">-->
                            <!--        <label for="user" class="label">Username</label>-->
                                    <!--<input id="user" type="text" class="input">-->
                            <!--        {{ user_form.username }}-->
                            <!--    </div>-->
                            <!--    <div class="group">-->
                            <!--        <label for="pass" class="label">Password</label>-->
                                    <!--<input id="pass" type="password" class="input" data-type="password">-->
                            <!--        {{ user_form.password1 }}-->
                            <!--    </div>-->
                            <!--    <div class="group">-->
                            <!--        <label for="pass" class="label">Repeat Password</label>-->
                                    <!--<input id="pass" type="password" class="input" data-type="password">-->
                            <!--        {{ user_form.password2 }}-->
                            <!--    </div>-->
                            <!--    <div class="group">-->
                            <!--        <label for="pass" class="label">Email Address</label>-->
                                    <!--<input id="pass" type="text" class="input">-->
                            <!--        {{ user_form.email }}-->
                            <!--    </div>-->
                            <!--    <div class="group">-->
                            <!--        <input type="submit" class="button" value="Sign Up">-->
                            <!--    </div>-->
                            <!--    <div class="hr"></div>-->
                            <!--    <div class="foot-lnk">-->
                            <!--        <label for="tab-1">이미 회원이시라면!</a>-->
                            <!--    </div>-->
                            <!--</div>-->
                        </div>
                    </div>
                
            </form>
        </div>

    </section>


</body>

</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'accounts/signin.css' %}">
    <link rel="stylesheet" media="(max-width:600px)" href="{% static 'accounts/signin-2-small.css' %}">
    <link rel="icon" href="{% static 'favicon.png' %}" sizes="16x16" type="image/png">
    <title>Blockbuster - signin</title>
</head>

<body>

    <div id="background"></div>

    <section id="signup">

        <!-- 메인으로 연결 -->
        <div id="signup-logo">
            <a href="{% url 'movies:movie_index' %}"><img src="{% static 'logo.png' %}" alt=""></a>
        </div>

        <!-- 로그인 폼 -->
        <div id="login-box">
            <form action="" method="POST">
                {% csrf_token %}
                    <div class="login-html">
                        <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1"
                            class="tab">Sign In</label>
                        <input id="tab-1" type="radio" name="tab" class="sign-up"><label for="tab-1" class="tab">
                            <!--SignUp-->
                            </label>
                        <div class="login-form">
                            <!--<div class="sign-in-htm">-->
                            <!--    <div class="group">-->
                            <!--        <label for="user" class="label">Username</label>-->
                            <!--        <input id="user" type="text" class="input">-->
                            <!--        {{login_form.username}}-->
                            <!--    </div>-->
                            <!--    <div class="group">-->
                            <!--        <label for="pass" class="label">Password</label>-->
                            <!--        <input id="pass" type="password" class="input" data-type="password">-->
                            <!--        {{login_form.password}}-->
                            <!--    </div>-->
                            <!--    <div class="group">-->
                            <!--        <input type="submit" class="button" value="Sign In">-->
                            <!--    </div>-->
                            <!--    <div class="hr"></div>-->
                            <!--    <div class="foot-lnk">-->
                            <!--        <a href="{% url 'accounts:signup' %}">회원가입</a><br><br><br><br>-->
                            <!--        <a href="#forgot">비밀번호를 잊으셨나요?</a>-->
                            <!--    </div>-->
                            <!--</div>-->
                            <div class="sign-in-htm">
                                <div class="group">
                                    <label for="user" class="label">Username</label>
                                    <!--<input id="user" type="text" class="input">-->
                                    {{ user_form.username }}
                                </div>
                                <div class="group">
                                    <label for="pass" class="label">Password</label>
                                    <!--<input id="pass" type="password" class="input" data-type="password">-->
                                    {{ user_form.password1 }}
                                </div>
                                <div class="group">
                                    <label for="pass" class="label">Repeat Password</label>
                                    <!--<input id="pass" type="password" class="input" data-type="password">-->
                                    {{ user_form.password2 }}
                                </div>
                                <div class="group">
                                    <label for="pass" class="label">Email Address</label>
                                    <!--<input id="pass" type="text" class="input">-->
                                    {{ user_form.email }}
                                </div>
                                <div class="group">
                                    <input type="submit" class="button" value="Sign Up">
                                </div>
                                <div class="hr"></div>
                                <div class="foot-lnk">
                                    <label for="tab-1"><a href="{% url 'accounts:login' %}">이미 회원이시라면!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                
            </form>
        </div>

    </section>

</body>

</html>