actors/urls.py
from django.urls import path
from . import views

app_name = 'actors'

urlpatterns = [
    path('', views.actors_list, name='actors_list'), 
    path('<int:actor_pk>/', views.actor_detail, name='actor_detail'), 
]

movie_recommend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('actors/', include('actors.urls')),
    
    # OAuth 적용 위함
    path('accounts/', include('allauth.urls')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('', views.index, name="movie_index"), 
    path('movielist/', views.movie_lists, name='movie_list'), ##
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'), 
    path('genre/', views.genre_list, name='genre_list'), 
    path('genre/<int:genre_id>/', views.genre_movies, name='genre_movies'), 
    path('director/<int:director_id>/', views.director, name='director'),
    
    # score 를 삭제하는 url입니다. score 생성은 movie_detail에서 다루고 있습니다.
    path('<int:movie_id>/delete_score/<int:score_id>/', views.delete_score, name="delete_score"), 
    
    # 추천하는 영화를 출력하는 url
    path('out_movie/', views.out_movie, name="out_movie"),
    
    # 첫 화면에서 review it 하면 전체 영화 리스트를 보여주고, 해당 영화의 이미지를 누르면 detail로 이동하게 됩니다.
    path('evaluate/', views.movie_evaluate, name="movie_evaluate"),
    
    # movie_list.html 에서 영화를 검색하면 해당 영화이름을 가지고 있는 영화들을 보여줍니다.
    path('search_movie/<str:movie_title>/', views.search_movie, name="search_movie"),
    
    #
    path('view_movies/<str:movie_title>', views.view_movies, name="view_movies"),
]

actors/models.py
from django.db import models
from django.conf import settings
from movies.models import Genre, Movie

# Create your models here.
class Actor(models.Model):
    name = models.CharField(max_length=100) #김슬기가 가져올 수 있음
    image = models.ImageField(blank=True) #김슬기가 가져올 수 있음
    twitter = models.CharField(max_length=100,blank=True)
    instagram = models.CharField(max_length=100,blank=True)
    facebook = models.CharField(max_length=100,blank=True)
    birthday = models.CharField(max_length=40,blank=True) #김슬기가 가져올 수 있음
    movies = models.ManyToManyField(Movie,related_name="movie_actors",blank=True) #김슬기가 가져올 수 있음
    
    def __str__(self):
        return 'Actor name : {}'.format(self.name)



class Prize(models.Model):
    name = models.CharField(max_length=100)
    actors = models.ManyToManyField(Actor,related_name="actor_prizes",blank=True)
    movies = models.ManyToManyField(Movie,related_name="movie_prizes",blank=True)
    date = models.CharField(max_length=40,blank=True)
    
    def __str__(self):
        return 'Prize name : {}'.format(self.name)

actors/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

# Create your views here.
def actors_list(request):
    actors = Actor.objects.all()
    context={'actors':actors}
    return render(request,'actors/actors_list.html',context)
    
def actor_detail(request, actor_pk):
    actor = get_object_or_404(Actor, pk=actor_pk)
    context={'actor':actor}
    return render(request,'actors/actor_detail.html',context)
    

actors/templates/actors/actors_list.html
{% extends 'base.html' %}
{% block body %}
    <h1>배우 목록</h1>
    <ul>
    {% for actor in actors %}
        <li>
            <img src="{{actor.imageurl}}" alt="" width="100px" height="100px"><br>
            
            <a href="{% url 'actors:actor_detail' actor.pk %}">{{actor.name}}</a><br>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

actors/templates/actors/detail.actor.html
{% extends 'base.html' %}
{% block body %}
    <hr>
    <h1>{{actor.name}}</h1>
    <img src="{{actor.image}}" width="480px" height="480px"><br>
    
    {% if user.pk %}
    <a href="#">좋은 배우 추가</a>
    <% endif %}
    
    {% if actor.instagram %}
        <a href="{{actor.instagram}}"><img src="{% static 'actors/instagram_icon.png' %}" width="22px" height="22px"></a><br>
    {% endif %}
    {% if actor.twitter %}
        <a href="{{actor.twitter}}"><img src="{% statics 'actors/twitter_icon.png' %}" width="22px" height="225px"></a><br>
    {% endif %}
    {% if actor.facebook %}
        <a href="{{actor.facebook}}"><img src="{% statics 'actors/facebook_icon.png' %}" width="22px" height="22px"></a><br>
    {% endif %}
    
    <p>생일 : {{actor.birthday}}</p>
    
    <hr>
    <h3>츨현 영화</h3>
    <ul>
    {% for movie in actor.movies.all %}
        <li>
            <img src="{{movie.imageurl}}" width="480px" height="480px"><br>
            <a href="{% url 'movies:movie_detail' movie.pk  %}">{{movie.title}}</a>
        </li>
    {% endfor %}
    </ul>
    
    <hr>
    <h3>수상 목록</h3>
    <ul>
    {% for prize in actor.actor_prize.all %}
        <li>
            <h5>{{prize.name}}</h5>
            <p>date : {{prize.name}}</p>
            {% for prize_movie in prize.movies.all %}
                {% if prize_movie in actor.movies.all %}
                    <p><a href="{% url 'movies:movie_detail' prize_movie.pk  %}">{{prize_movie.title}}</a></p>
                {% endif %}
            {% endfor %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

actors/templates/actors/list_actors.html
{% extends 'base.html' %}
{% block body %}
    <hr>
    <h1>배우 목록</h1>
    <ul>
    {% for actor in actors %}
        <li>
            <img src="{{actor.image}}" width="100px" height="100px"><br>
            <p>{{actor.name}}</p>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

actors/templates/actors/list_prizes.html
{% extends 'base.html' %}
{% block body %}
    <hr>
    <h1>수상 목록</h1>
    <ul>
    {% for prize in prizes %}
        <li>
            <h3>{{prize.name}}</h3>
            <p>수상 배우</p>
            <ul>
            {% for actor in prize.actors.all %}
                    <li><a href="{% url 'actors:actor_detail' actor.pk  %}">{{actor.name}}</a></li>
            {% endfor %}
            </ul><br>
            
            <p>수상작</p>
            <ul>
            {% for movie in prize.movies.all %}
                    <li><a href="{% url 'movies:movie_detail' movie.pk  %}">{{movie.title}}</a></li>
            {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
{% endblock %}